name: Bug report
description: Report reproducible incorrect behavior
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Minimal reproduction
    validations:
      required: true
